# Generated by Django 3.2 on 2021-05-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0006_deviationfromgroup"),
        ("parlacards", "0006_personavgspeechespersession"),
    ]

    operations = []
