# Generated by Django 3.2 on 2021-05-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0010_personmonthlypresenceonvote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personmonthlypresenceonvote",
            old_name="not_a_member",
            new_name="no_mandate",
        ),
    ]
