# Generated by Django 3.2 on 2021-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0010_auto_20210531_1429"),
        (
            "parlacards",
            "0011_rename_not_a_member_personmonthlypresenceonvote_no_mandate",
        ),
    ]

    operations = []
