# Generated by Django 3.2.3 on 2021-06-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parlacards", "0010_personstylescore"),
        ("parlacards", "0015_groupnumberofquestions"),
    ]

    operations = []
