# Generated by Django 3.2.3 on 2021-06-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0030_speech_lemmatized_content"),
        ("parlacards", "0019_groupvoteattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingdistance",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_people",
                to="parladata.person",
            ),
        ),
        migrations.CreateModel(
            name="GroupVotingDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupvotingdistance_related",
                        to="parladata.organization",
                    ),
                ),
                (
                    "playing_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.organization",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_organizations",
                        to="parladata.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
