# Generated by Django 3.2.5 on 2021-07-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0035_auto_20210715_1704"),
        ("parlacards", "0025_sessiongroupattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviationfromgroup",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deviationfromgroup_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personavgspeechespersession",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personavgspeechespersession_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personmonthlyvoteattendance",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personmonthlyvoteattendance_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofquestions",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnumberofquestions_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofspokenwords",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnumberofspokenwords_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personstylescore",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personstylescore_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="persontfidf",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persontfidf_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personvocabularysize",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personvocabularysize_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personvoteattendance",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personvoteattendance_related",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="votingdistance",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votingdistance_related",
                to="parladata.person",
            ),
        ),
    ]
