# Generated by Django 3.2.7 on 2021-09-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0045_auto_20210913_1845"),
        ("parlacards", "0026_auto_20210726_1848"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "quote_content",
                    models.TextField(
                        blank=True, help_text="text quoted in a speech", null=True
                    ),
                ),
                (
                    "start_index",
                    models.IntegerField(
                        blank=True,
                        help_text="index of first character of quote string",
                        null=True,
                    ),
                ),
                (
                    "end_index",
                    models.IntegerField(
                        blank=True,
                        help_text="index of last character of quote string",
                        null=True,
                    ),
                ),
                (
                    "speech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="parladata.speech",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
