# Generated by Django 5.0.7 on 2024-10-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlacards', '0028_auto_20221201_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVoteDiscord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_vote_discords', to='parladata.organization')),
                ('playing_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parladata.organization')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_vote_discords', to='parladata.vote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
