# Generated by Django 3.1.2 on 2021-04-09 13:48

from django.db import migrations
import parladata.models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_of_answer',
            field=parladata.models.PopoloDateTimeField(blank=True, help_text='Date of answer the question.', null=True),
        ),
    ]
