# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import parladata.models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('start_time', parladata.models.PopoloDateTimeField(blank=True, help_text=b'Start time', null=True)),
                ('end_time', parladata.models.PopoloDateTimeField(blank=True, help_text=b'End time', null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that is a party to the relationship', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='parladata.Organization')),
                ('parent', models.ForeignKey(blank=True, help_text='The organization which is parent in the relationship', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_parent_memberships', to='parladata.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
