# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-03-04 14:21
from __future__ import unicode_literals

from django.db import migrations
import parladata.models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_of_answer',
            field=parladata.models.PopoloDateTimeField(blank=True, help_text=b'Date of answer the question.', null=True),
        ),
    ]
