# Generated by Django 3.1.2 on 2021-04-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0003_auto_20210423_1301"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Membership",
            new_name="PersonMembership",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="mandate",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="person",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="session",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="speech",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="post",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="post",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="source",
            name="contact_detail",
        ),
        migrations.RemoveField(
            model_name="source",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="source",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="source",
            name="person",
        ),
        migrations.RemoveField(
            model_name="source",
            name="post",
        ),
        migrations.RemoveField(
            model_name="source",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="question",
            name="recipient_post",
        ),
        migrations.DeleteModel(
            name="ContactDetail",
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Source",
        ),
    ]
