# Generated by Django 3.2 on 2021-05-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0005_auto_20210423_1548"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "People"},
        ),
        migrations.RenameField(
            model_name="area",
            old_name="calssification",
            new_name="classification",
        ),
        migrations.RemoveField(
            model_name="person",
            name="name",
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="A date of birth",
                null=True,
                verbose_name="date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(
                blank=True,
                help_text="A date of death",
                null=True,
                verbose_name="date of death",
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="valid_from",
            field=models.DateTimeField(auto_now_add=True, help_text="row valid from"),
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="parladata.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
