# Generated by Django 3.2 on 2021-05-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0006_auto_20210505_2202"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonEducationLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonHonorificPrefix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonHonorificSuffix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonNumberOfMandates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonNumberOfPoints",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonNumberOfVoters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonPreferredPronoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonPreviousOccupation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PersonEducation",
        ),
        migrations.RemoveField(
            model_name="person",
            name="education",
        ),
        migrations.RemoveField(
            model_name="person",
            name="education_level",
        ),
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="honorific_prefix",
        ),
        migrations.RemoveField(
            model_name="person",
            name="honorific_suffix",
        ),
        migrations.RemoveField(
            model_name="person",
            name="number_of_mandates",
        ),
        migrations.RemoveField(
            model_name="person",
            name="number_of_points",
        ),
        migrations.RemoveField(
            model_name="person",
            name="number_of_voters",
        ),
        migrations.RemoveField(
            model_name="person",
            name="preferred_pronoun",
        ),
        migrations.RemoveField(
            model_name="person",
            name="previous_occupation",
        ),
        migrations.AlterField(
            model_name="personname",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personpreviousoccupation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personpreferredpronoun",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personnumberofvoters",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personnumberofpoints",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personnumberofmandates",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personhonorificsuffix",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personhonorificprefix",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personemail",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.AddField(
            model_name="personeducationlevel",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parladata.person"
            ),
        ),
        migrations.CreateModel(
            name="PersonEducation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(auto_now_add=True, help_text="row valid from"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
