# Generated by Django 3.2 on 2021-05-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0008_auto_20210510_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationname",
            name="acronym",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="name",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="parser_names",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="organizationname",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="organizationname",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="parladata.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationname",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AddField(
            model_name="organizationname",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid to", null=True
            ),
        ),
        migrations.AddField(
            model_name="organizationname",
            name="value",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personeducation",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personeducationlevel",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personemail",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personhonorificprefix",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personhonorificsuffix",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personname",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofmandates",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofpoints",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofvoters",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personpreferredpronoun",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="personpreviousoccupation",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, default=None, help_text="row valid from", null=True
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAcronym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid from", null=True
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("value", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
