# Generated by Django 3.2 on 2021-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0009_auto_20210510_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personeducationlevel",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="personnumberofmandates",
            name="value",
            field=models.IntegerField(),
        ),
    ]
