# Generated by Django 3.2 on 2021-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0010_auto_20210510_2016"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="parser_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
