# Generated by Django 3.2 on 2021-05-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0011_organization_parser_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personmembership",
            name="label",
        ),
        migrations.AlterField(
            model_name="personmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that is a party to the relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="parladata.organization",
            ),
        ),
        migrations.AlterField(
            model_name="personmembership",
            name="person",
            field=models.ForeignKey(
                help_text="The person who is a party to the relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="parladata.person",
            ),
        ),
        migrations.AlterField(
            model_name="personnumberofpoints",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="personnumberofvoters",
            name="value",
            field=models.IntegerField(),
        ),
    ]
