# Generated by Django 3.2 on 2021-05-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0014_auto_20210511_1155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="session",
            name="tags",
        ),
        migrations.AlterField(
            model_name="session",
            name="gov_id",
            field=models.TextField(blank=True, help_text="Gov website ID.", null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="in_review",
            field=models.BooleanField(
                default=False, help_text="Is session still in review?"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="mandate",
            field=models.ForeignKey(
                default=1,
                help_text="The mandate of this session.",
                on_delete=django.db.models.deletion.CASCADE,
                to="parladata.mandate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="name",
            field=models.TextField(help_text="Session name"),
        ),
        migrations.AlterField(
            model_name="session",
            name="organizations",
            field=models.ManyToManyField(
                help_text="The organization(s) in session",
                related_name="sessions",
                to="parladata.Organization",
            ),
        ),
    ]
