# Generated by Django 3.2 on 2021-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0021_auto_20210511_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="passed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
