# Generated by Django 3.2 on 2021-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0023_alter_personmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motion",
            name="champions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The people who proposed the motion.",
                null=True,
                to="parladata.Person",
            ),
        ),
    ]
