# Generated by Django 3.2 on 2021-05-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0024_alter_motion_champions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="mandate",
            field=models.ForeignKey(
                help_text="The mandate of this session.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="parladata.mandate",
            ),
        ),
    ]
