# Generated by Django 3.2 on 2021-05-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0025_alter_session_mandate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="datetime",
            new_name="timestamp",
        ),
    ]
