# Generated by Django 3.2 on 2021-05-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0027_vote_needs_editing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="answer_datetime",
            new_name="answer_timestamp",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="datetime",
            new_name="timestamp",
        ),
    ]
