# Generated by Django 3.2 on 2021-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0029_auto_20210524_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="speech",
            name="lemmatized_content",
            field=models.TextField(
                blank=True, help_text="Lemmatized words spoken", null=True
            ),
        ),
    ]
