# Generated by Django 3.2.3 on 2021-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0030_speech_lemmatized_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandate",
            name="beginning",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
