# Generated by Django 3.2.4 on 2021-06-16 16:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('parladata', '0030_speech_lemmatized_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
