# Generated by Django 3.2.4 on 2021-06-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0031_speech_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='motion',
            field=models.ForeignKey(blank=True, help_text='Vote on speech', null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.motion'),
        ),
    ]
