# Generated by Django 3.2.4 on 2021-06-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0032_auto_20210617_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="vote",
            field=models.ForeignKey(
                help_text="The vote event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to="parladata.vote",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="result",
            field=models.BooleanField(
                blank=True, help_text="Did the motion pass?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="result",
            field=models.BooleanField(
                blank=True, help_text="The result of the vote", null=True
            ),
        ),
    ]
