# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import parladata.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('parladata', '0033_speech_version_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('name', models.TextField(blank=True, help_text=b'The name of agenda', null=True)),
                ('date', parladata.models.PopoloDateTimeField(blank=True, help_text=b'Date of the item.', null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.Session')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_parser',
            field=models.CharField(blank=True, help_text=b'Name for parser.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='agenda_item',
            field=models.ForeignKey(blank=True, help_text=b'Agenda item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parladata.AgendaItem'),
        ),
    ]
