# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0034_auto_20180523_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentMember',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('parladata.person',),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='order',
            field=models.IntegerField(blank=True, help_text=b'Order of agenda item', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='signature',
            field=models.TextField(blank=True, help_text='Unique signature', null=True, verbose_name='Unique signature'),
        ),
        migrations.AddField(
            model_name='vote',
            name='counter',
            field=models.TextField(blank=True, help_text='Counter of ballot option', null=True, verbose_name='json'),
        ),
    ]
