# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0034_auto_20180523_1404'),
        ('parladata', '0035_auto_20180605_1409'),
    ]

    operations = [
    ]
