# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0036_merge_20180719_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='mdt',
            field=models.CharField(blank=True, help_text=b'Working body text', max_length=1024, null=True),
        ),
    ]
