# Generated by Django 3.2.5 on 2021-08-17 18:12

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("parladata", "0037_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParliamentaryGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("parladata.organization",),
        ),
        migrations.AlterField(
            model_name="personpreferredpronoun",
            name="value",
            field=models.TextField(
                choices=[("he", "he"), ("she", "she"), ("they", "they")]
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="time when started",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="time when finished",
                        null=True,
                    ),
                ),
                (
                    "errored_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="time when errored",
                        null=True,
                    ),
                ),
                ("name", models.TextField(help_text="Name of task")),
                ("payload", models.JSONField(default={}, help_text="Payload kwargs")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
