# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0037_auto_20180719_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='order',
            field=models.IntegerField(blank=True, help_text=b'Order of agenda item', null=True),
        ),
    ]
