# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0038_agendaitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_orgs',
            field=models.ManyToManyField(blank=True, help_text=b'The organizations of person (MP) who asked the question.', to='parladata.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text=b'The persons (MP) who asked the question.', to='parladata.Person'),
        ),
    ]
