# Generated by Django 3.2.5 on 2021-08-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0039_auto_20210827_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="agenda_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The agenda item this link belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="parladata.agendaitem",
            ),
        ),
    ]
