# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models

def forward(apps, schema_editor):
    Questions = apps.get_model("parladata", "Question")
    for question in Questions.objects.all():
    	if question.author:
        	question.authors.add(question.author)
        if question.author_org:
        	question.author_orgs.add(question.author_org)


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0039_auto_20180829_1524'),
    ]

    operations = [
    	migrations.RunPython(forward)
    ]
