# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0040_auto_20180829_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author_org',
        ),
    ]
