# Generated by Django 3.2.5 on 2021-08-27 09:06

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0040_link_agenda_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaitem",
            name="text",
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
