# Generated by Django 3.2.5 on 2021-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0041_agendaitem_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("for", "for"),
                    ("against", "against"),
                    ("abstain", "abstain"),
                    ("absent", "absent"),
                ],
                help_text="Yes, no, abstain",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="classification",
            field=models.CharField(
                choices=[
                    ("regular", "regular"),
                    ("irregular", "regular"),
                    ("correspondent", "correspondent"),
                ],
                default="regular",
                help_text="Session classification",
                max_length=128,
            ),
        ),
    ]
