# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import parladata.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('parladata', '0041_auto_20180829_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('order', models.IntegerField(blank=True, help_text=b'Order of debate', null=True)),
                ('date', parladata.models.PopoloDateTimeField(blank=True, help_text=b'Date of the item.', null=True)),
                ('gov_id', models.CharField(blank=True, help_text=b'gov_id of debate', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='gov_id',
            field=models.CharField(blank=True, help_text=b'gov_id of agenda item', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motion',
            name='agenda_item',
            field=models.ForeignKey(blank=True, help_text=b'Agenda item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='parladata.AgendaItem'),
        ),
        migrations.AddField(
            model_name='debate',
            name='agenda_item',
            field=models.ForeignKey(blank=True, help_text=b'Agenda item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='parladata.AgendaItem'),
        ),
        migrations.AddField(
            model_name='debate',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.Session'),
        ),
        migrations.AddField(
            model_name='debate',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='speech',
            name='debate',
            field=models.ForeignKey(blank=True, help_text=b'Debates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parladata.Debate'),
        ),
    ]
