# Generated by Django 3.2.7 on 2021-09-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0044_auto_20210911_1135"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="mandate",
        ),
        migrations.AlterField(
            model_name="law",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("in_procedure", "in_procedure"),
                    ("enacted", "enacted"),
                    ("submitted", "submitted"),
                    ("rejected", "rejected"),
                    ("adopted", "adopted"),
                    ("received", "received"),
                    ("retracted", "retracted"),
                ],
                help_text="Status of law",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizationmemberships",
                to="parladata.mandate",
                verbose_name="Mandate",
            ),
        ),
        migrations.AlterField(
            model_name="personmembership",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personmemberships",
                to="parladata.mandate",
                verbose_name="Mandate",
            ),
        ),
    ]
