# Generated by Django 3.2.7 on 2021-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0046_auto_20211025_1620"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationlevel",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
