# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0046_question_type_of_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='party',
            field=models.ForeignKey(blank=True, default=2, help_text=b'The party of the person making the speech', null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.Organization'),
        ),
    ]
