# Generated by Django 3.2.9 on 2021-11-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0047_auto_20211102_1401"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.TextField(help_text="Medium name", verbose_name="name"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Medium URL", max_length=255, verbose_name="url"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "title",
                    models.TextField(help_text="Report title", verbose_name="title"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Report URL", max_length=500, verbose_name="url"
                    ),
                ),
                ("report_date", models.DateField()),
                ("retrieval_date", models.DateTimeField()),
                (
                    "medium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="parladata.medium",
                    ),
                ),
                (
                    "mentioned_legislation",
                    models.ManyToManyField(
                        blank=True, related_name="media_reports", to="parladata.Law"
                    ),
                ),
                (
                    "mentioned_motions",
                    models.ManyToManyField(
                        blank=True, related_name="media_reports", to="parladata.Motion"
                    ),
                ),
                (
                    "mentioned_organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="media_reports",
                        to="parladata.Organization",
                    ),
                ),
                (
                    "mentioned_people",
                    models.ManyToManyField(
                        blank=True, related_name="media_reports", to="parladata.Person"
                    ),
                ),
                (
                    "mentioned_votes",
                    models.ManyToManyField(
                        blank=True, related_name="media_reports", to="parladata.Vote"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
