# Generated by Django 3.2.9 on 2021-11-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0048_mediareport_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediareport',
            name='uri',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.TextField(blank=True, choices=[('question', 'question'), ('initiative', 'initiative')], null=True),
        ),
    ]
