# Generated by Django 3.2.9 on 2021-11-26 08:51

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0048_mediareport_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="uri",
            field=models.TextField(
                db_index=True, default="", help_text="Medium URI", verbose_name="uri"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="text",
            field=martor.models.MartorField(
                blank=True, null=True, verbose_name="Agenda item content"
            ),
        ),
        migrations.AlterField(
            model_name="mediareport",
            name="retrieval_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="classification",
            field=models.TextField(
                blank=True,
                choices=[
                    ("root", "root"),
                    ("pg", "pg"),
                    ("commission", "commission"),
                    ("committee", "committee"),
                    ("council", "council"),
                    ("delegation", "delegation"),
                    ("friendship_group", "friendship_group"),
                    ("investigative_commission", "investigative_commission"),
                    ("other", "other"),
                ],
                help_text="An organization category, e.g. committee",
                null=True,
                verbose_name="classification",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type_of_question",
            field=models.TextField(
                blank=True,
                choices=[("question", "question"), ("initiative", "initiative")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="classification",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("regular", "regular"),
                    ("irregular", "irregular"),
                    ("correspondent", "correspondent"),
                    ("urgent", "urgent"),
                ],
                default="unknown",
                help_text="Session classification",
                max_length=128,
            ),
        ),
    ]
