# Generated by Django 3.2.9 on 2021-11-24 18:29

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0048_mediareport_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(blank=True, help_text='Status of legisaltion', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.TextField(blank=True, help_text='Name of procedure type', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='text',
            field=martor.models.MartorField(blank=True, null=True, verbose_name='Agenda item content'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.TextField(blank=True, choices=[('root', 'root'), ('pg', 'pg'), ('commission', 'commission'), ('committee', 'committee'), ('council', 'council'), ('delegation', 'delegation'), ('friendship_group', 'friendship_group'), ('investigative_commission', 'investigative_commission'), ('other', 'other')], help_text='An organization category, e.g. committee', null=True, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.TextField(blank=True, choices=[('question', 'question'), ('initiative', 'initiative')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='classification',
            field=models.CharField(choices=[('unknown', 'unknown'), ('regular', 'regular'), ('irregular', 'irregular'), ('correspondent', 'correspondent'), ('urgent', 'urgent')], default='unknown', help_text='Session classification', max_length=128),
        ),
        migrations.CreateModel(
            name='ProcedurePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(blank=True, help_text='Name of procedure phase', null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parladata.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegislationConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Date of the law.', null=True)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parladata.law')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization in which consideration happened', null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.organization')),
                ('procedure_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parladata.procedurephase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='law',
            name='considerations',
            field=models.ManyToManyField(blank=True, help_text='Consideration of legislation', through='parladata.LegislationConsideration', to='parladata.ProcedurePhase'),
        ),
        migrations.AddField(
            model_name='link',
            name='legislation_consideration',
            field=models.ForeignKey(blank=True, help_text='The legislation consideration this link belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='parladata.legislationconsideration'),
        ),
        migrations.AlterField(
            model_name='law',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.legislationstatus'),
        ),
    ]
