# Generated by Django 3.2.9 on 2021-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0050_mediareport_uri"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="authors",
            new_name="person_authors",
        ),
    ]
