# Generated by Django 3.2.9 on 2021-12-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0053_auto_20211201_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(blank=True, help_text='Status of legisaltion', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='motion',
            name='law',
            field=models.ForeignKey(blank=True, help_text='Piece of legislation this motion is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='parladata.law'),
        ),
        migrations.AlterField(
            model_name='law',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.legislationclassification'),
        ),
    ]
