# Generated by Django 3.2.10 on 2022-02-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0059_auto_20220215_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationconsideration',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session at which the legislation was discussed', null=True, on_delete=django.db.models.deletion.CASCADE, to='parladata.session'),
        ),
        migrations.AlterField(
            model_name='organizationacronym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationacronym', to='parladata.organization'),
        ),
        migrations.AlterField(
            model_name='organizationemail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationemail', to='parladata.organization'),
        ),
        migrations.AlterField(
            model_name='organizationname',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationname', to='parladata.organization'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personeducation', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personeducationlevel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personeducationlevel', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personemail', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personhonorificprefix',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personhonorificprefix', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personhonorificsuffix',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personhonorificsuffix', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personname',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personname', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personnumberofmandates',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnumberofmandates', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personnumberofpoints',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnumberofpoints', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personnumberofvoters',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnumberofvoters', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personpreferredpronoun',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personpreferredpronoun', to='parladata.person'),
        ),
        migrations.AlterField(
            model_name='personpreviousoccupation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personpreviousoccupation', to='parladata.person'),
        ),
    ]
