# Generated by Django 3.2.12 on 2022-05-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0061_auto_20220309_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'verbose_name': 'Law', 'verbose_name_plural': 'Legislation'},
        ),
        migrations.AddField(
            model_name='mandate',
            name='ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislationconsideration',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session at which the legislation was discussed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legislation_considerations', to='parladata.session'),
        ),
    ]
