# Generated by Django 3.2.12 on 2022-12-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0067_question_mandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(help_text='Text of question')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_person', models.ForeignKey(help_text='Recipient person.', on_delete=django.db.models.deletion.CASCADE, related_name='received_person_questions', to='parladata.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(help_text='Text of answer')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='parladata.personquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
