# Generated by Django 3.2.12 on 2022-12-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0068_publicpersonanswer_publicpersonquestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicpersonanswer",
            old_name="notification_set_at",
            new_name="notification_sent_at",
        ),
        migrations.RenameField(
            model_name="publicpersonquestion",
            old_name="notification_set_at",
            new_name="notification_sent_at",
        ),
    ]
