# Generated by Django 3.2.12 on 2023-11-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parladata', '0075_auto_20230530_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.TextField(blank=True, choices=[('root', 'root'), ('pg', 'pg'), ('commission', 'commission'), ('committee', 'committee'), ('council', 'council'), ('delegation', 'delegation'), ('friendship_group', 'friendship_group'), ('investigative_commission', 'investigative_commission'), ('other', 'other'), ('coalition', 'coalition'), ('party', 'party')], help_text='An organization category, e.g. committee', null=True, verbose_name='classification'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Date of the question.', null=True)),
                ('content', models.TextField(blank=True, help_text='Title name as written on dz-rs.si', null=True)),
                ('organization_authors', models.ManyToManyField(blank=True, help_text="Recipient organization (if it's an organization).", related_name='answers_org_author', to='parladata.Organization')),
                ('person_authors', models.ManyToManyField(blank=True, help_text='The persons (MP) who asked the question.', related_name='authored_ansewrs', to='parladata.Person')),
                ('question', models.ForeignKey(help_text='The question this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, to='parladata.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='link',
            name='answer',
            field=models.ForeignKey(blank=True, help_text='The answer this link belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='parladata.answer'),
        ),
    ]
